# ONLIMO historical daily Pollution Index extractor
#
# Purpose:
#   Retrieve historical daily composite Pollution Index (IP) from
#   trendWeekChart using conservative 7-day requests.
#
# Design:
#   - Station selection comes from onlimo_station_catalog.csv generated by
#     01_onlimo_daily_archive.R.
#   - Default scope is five watersheds: Ciliwung, Cisadane, Citarum,
#     Bengawan Solo, and Musi.
#   - A request ledger records completed station/block queries, including
#     genuinely empty periods. This makes the script safely resumable.
#   - Data and ledger are checkpointed regularly, so interruption does not
#     require starting again from the beginning.
#   - Requests are sequential and deliberately paced; no parallel requests.

suppressPackageStartupMessages({
  library(httr2)
  library(dplyr)
  library(purrr)
  library(tibble)
  library(readr)
  library(tidyr)
})

# =============================================================================
# 1. USER CONFIGURATION
# =============================================================================

TELITI_DATA_ROOT <- Sys.getenv(
  "TELITI_DATA_ROOT",
  unset = "D:/# R Project/penelitian"
)

PROJECT_DIR <- file.path(TELITI_DATA_ROOT, "onlimo")
DATA_DIR    <- file.path(PROJECT_DIR, "data")
LOG_DIR     <- file.path(PROJECT_DIR, "log")

COLLECTOR_TZ <- Sys.getenv(
  "TELITI_TIMEZONE",
  unset = "Asia/Taipei"
)

COLLECTOR_ID <- Sys.getenv(
  "TELITI_COLLECTOR_ID",
  unset = "local_pc"
)

GITHUB_RUN_ID <- Sys.getenv("GITHUB_RUN_ID", unset = "")
GITHUB_RUN_ATTEMPT <- Sys.getenv("GITHUB_RUN_ATTEMPT", unset = "")
GITHUB_SHA <- Sys.getenv("GITHUB_SHA", unset = "")

PARTITION_MODE <- tolower(
  Sys.getenv(
    "ONLIMO_IP_PARTITION_MODE",
    unset = if (identical(COLLECTOR_ID, "github_actions")) "true" else "false"
  )
) %in% c("1", "true", "yes", "y")

BASE_PAGE <- "https://onlimo.kemenlh.go.id/app/"
BASE_API  <- "https://onlimo.kemenlh.go.id/app/index"

CATALOG_FILE <- file.path(DATA_DIR, "onlimo_station_catalog.csv")
DATA_FILE <- file.path(DATA_DIR, "onlimo_pollution_index_historical.csv")
LEDGER_FILE <- file.path(DATA_DIR, "onlimo_pollution_index_request_ledger.csv")
COVERAGE_FILE <- file.path(DATA_DIR, "onlimo_pollution_index_coverage_station.csv")
MONTHLY_FILE <- file.path(DATA_DIR, "onlimo_pollution_index_summary_monthly.csv")

# Cloud-friendly per-run products. These are deliberately separate from the
# cumulative Windows archive so GitHub can use append-oriented storage.
RUN_ROWS_FILE <- file.path(DATA_DIR, "onlimo_pollution_index_run_rows.csv.gz")
RUN_SUMMARY_FILE <- file.path(DATA_DIR, "onlimo_pollution_index_run_summary.csv")

# Scope options:
#   "selected_das"      = all stations in SELECTED_DAS
#   "all_catalog"       = every station in the current station catalogue
#   "explicit_stations" = only station IDs listed in EXPLICIT_STATIONS
SCOPE_MODE <- Sys.getenv(
  "ONLIMO_IP_SCOPE_MODE",
  unset = "selected_das"
)

SELECTED_DAS <- c(
  "Ciliwung",
  "Cisadane",
  "Citarum",
  "Bengawan Solo",
  "Musi"
)

EXPLICIT_STATIONS <- c(
  "KLHK4",
  "KLHK63",
  "KLHK122",
  "KLHK123"
)

# Optional station-category filter.
# Leave NULL to include both KLHK and INTEGRASI stations.
# Example: STATION_CATEGORY_FILTER <- "KLHK"
STATION_CATEGORY_FILTER <- NULL

# Historical range to attempt.
# Empty periods are legitimate and are recorded in the request ledger.
# START_DATE <- as.Date("2020-01-01")
# END_DATE   <- Sys.Date() - 1L
parse_config_date <- function(name, default_value) {
  value <- Sys.getenv(name, unset = "")

  if (!nzchar(value)) {
    return(as.Date(default_value))
  }

  if (tolower(value) == "yesterday") {
    return(Sys.Date() - 1L)
  }

  out <- suppressWarnings(as.Date(value))

  if (is.na(out)) {
    stop(
      name,
      " must be YYYY-MM-DD or 'yesterday'. Received: ",
      value
    )
  }

  out
}

START_DATE <- parse_config_date(
  "ONLIMO_IP_START_DATE",
  "2024-07-01"
)

END_DATE <- parse_config_date(
  "ONLIMO_IP_END_DATE",
  "2024-09-30"
)


# trendWeekChart has been verified with 7-day windows, so keep this conservative.
BLOCK_DAYS <- 7L

# Polite request pacing. Requests are intentionally sequential.
REQUEST_PAUSE_MIN_SEC <- 0.6
REQUEST_PAUSE_MAX_SEC <- 1.1

# Safety cap per execution. Because the request ledger is resumable, re-running
# the script continues where it stopped. Set to Inf after you are comfortable
# with the workflow and want a single long run.
MAX_REQUESTS_PER_RUN <- suppressWarnings(
  as.numeric(
    Sys.getenv(
      "ONLIMO_IP_MAX_REQUESTS_PER_RUN",
      unset = "3000"
    )
  )
)

if (is.na(MAX_REQUESTS_PER_RUN) || MAX_REQUESTS_PER_RUN <= 0) {
  stop("ONLIMO_IP_MAX_REQUESTS_PER_RUN must be a positive number.")
}

# Save data + ledger after this many requests.
CHECKPOINT_EVERY <- suppressWarnings(
  as.integer(
    Sys.getenv(
      "ONLIMO_IP_CHECKPOINT_EVERY",
      unset = "50"
    )
  )
)

if (is.na(CHECKPOINT_EVERY) || CHECKPOINT_EVERY <= 0L) {
  stop("ONLIMO_IP_CHECKPOINT_EVERY must be a positive integer.")
}

# If FALSE, station/block requests already recorded as successful or genuinely
# empty are skipped. Normally leave this FALSE.
REFRESH_COMPLETED_BLOCKS <- tolower(
  Sys.getenv(
    "ONLIMO_IP_REFRESH_COMPLETED",
    unset = "false"
  )
) %in% c("1", "true", "yes", "y")

# =============================================================================
# 2. SETUP AND LOGGING
# =============================================================================

dir.create(DATA_DIR, recursive = TRUE, showWarnings = FALSE)
dir.create(LOG_DIR, recursive = TRUE, showWarnings = FALSE)

run_started <- Sys.time()
log_file <- file.path(
  LOG_DIR,
  paste0(
    "historical_ip_",
    format(run_started, "%Y%m%d_%H%M%S", tz = COLLECTOR_TZ),
    ".log"
  )
)

log_msg <- function(...) {
  msg <- paste0(..., collapse = "")
  line <- paste0(
    format(Sys.time(), "%Y-%m-%d %H:%M:%S", tz = COLLECTOR_TZ),
    " | ",
    msg
  )
  cat(line, "\n")
  cat(line, "\n", file = log_file, append = TRUE)
}

retrieved_at_now <- function() {
  format(
    Sys.time(),
    "%Y-%m-%d %H:%M:%S%z",
    tz = COLLECTOR_TZ
  )
}

optional_env_value <- function(x) {
  if (nzchar(x)) x else NA_character_
}

# Per-run outputs must never inherit stale content from a previous local run.
unlink(RUN_ROWS_FILE, force = TRUE)
unlink(RUN_SUMMARY_FILE, force = TRUE)

safe_text <- function(x) {
  if (length(x) == 0 || is.null(x) || is.na(x)) return(NA_character_)
  as.character(x)[1]
}

# =============================================================================
# 3. LOAD AND SELECT STATIONS FROM THE DAILY-COLLECTOR CATALOGUE
# =============================================================================

if (!file.exists(CATALOG_FILE)) {
  stop(
    "Station catalogue not found: ", CATALOG_FILE,
    "\nRun 01_onlimo_daily_archive.R at least once first."
  )
}

catalog <- read_csv(
  CATALOG_FILE,
  col_types = cols(.default = col_character()),
  show_col_types = FALSE
) |>
  mutate(
    station_id = trimws(station_id),
    watershed = trimws(watershed),
    station_category = trimws(station_category),
    latitude = suppressWarnings(as.numeric(latitude)),
    longitude = suppressWarnings(as.numeric(longitude)),
    watershed_key = tolower(trimws(watershed))
  ) |>
  filter(!is.na(station_id), nzchar(station_id)) |>
  distinct(station_id, .keep_all = TRUE)

selected_das_key <- tolower(trimws(SELECTED_DAS))

if (SCOPE_MODE == "selected_das") {
  selected_catalog <- catalog |>
    filter(watershed_key %in% selected_das_key)

} else if (SCOPE_MODE == "all_catalog") {
  selected_catalog <- catalog

} else if (SCOPE_MODE == "explicit_stations") {
  selected_catalog <- catalog |>
    filter(station_id %in% EXPLICIT_STATIONS)

} else {
  stop(
    "Unknown SCOPE_MODE: ", SCOPE_MODE,
    ". Use selected_das, all_catalog, or explicit_stations."
  )
}

if (!is.null(STATION_CATEGORY_FILTER)) {
  selected_catalog <- selected_catalog |>
    filter(station_category %in% STATION_CATEGORY_FILTER)
}

selected_catalog <- selected_catalog |>
  arrange(watershed, station_id)

if (nrow(selected_catalog) == 0) {
  stop("No stations matched the configured scope.")
}

log_msg("START historical Pollution Index extraction")
log_msg("Scope mode: ", SCOPE_MODE)
log_msg("Collector ID: ", COLLECTOR_ID)
log_msg("Collector timezone: ", COLLECTOR_TZ)
log_msg("Partition mode: ", PARTITION_MODE)
log_msg("Date range: ", START_DATE, " to ", END_DATE)
log_msg("Block size: ", BLOCK_DAYS, " days")
log_msg("Maximum requests this run: ", MAX_REQUESTS_PER_RUN)
log_msg("Stations selected: ", nrow(selected_catalog))

scope_summary <- selected_catalog |>
  count(watershed, name = "n_stations") |>
  arrange(watershed)

for (i in seq_len(nrow(scope_summary))) {
  log_msg(
    "  DAS ", scope_summary$watershed[i],
    ": ", scope_summary$n_stations[i], " stations"
  )
}

# =============================================================================
# 4. DATE BLOCKS AND REQUEST PLAN
# =============================================================================

make_blocks <- function(start_date, end_date, block_days = 7L) {
  start_date <- as.Date(start_date)
  end_date <- as.Date(end_date)

  if (is.na(start_date) || is.na(end_date) || start_date > end_date) {
    stop("Invalid START_DATE / END_DATE configuration.")
  }

  starts <- seq(
    start_date,
    end_date,
    by = paste(block_days, "days")
  )

  ends <- starts + (block_days - 1L)
  ends[ends > end_date] <- end_date

  tibble(
    block_start = as.Date(starts),
    block_end = as.Date(ends)
  )
}

blocks <- make_blocks(START_DATE, END_DATE, BLOCK_DAYS)

plan <- tidyr::crossing(
  block_start = blocks$block_start,
  station_id = selected_catalog$station_id
) |>
  left_join(blocks, by = "block_start") |>
  arrange(block_start, station_id)

# =============================================================================
# 5. EXISTING ARCHIVE AND REQUEST LEDGER
# =============================================================================

empty_archive <- function() {
  tibble(
    station_id = character(),
    date = as.Date(character()),
    pollution_index = double(),
    pollution_status_derived = character(),
    station_name = character(),
    river = character(),
    watershed = character(),
    location_category = character(),
    river_segment = character(),
    station_category = character(),
    kabupaten_kota = character(),
    province = character(),
    latitude = double(),
    longitude = double(),
    source_endpoint = character(),
    retrieved_at = character()
  )
}

read_archive <- function() {
  if (!file.exists(DATA_FILE)) return(empty_archive())

  read_csv(
    DATA_FILE,
    col_types = cols(
      .default = col_guess(),
      station_id = col_character(),
      date = col_date(),
      retrieved_at = col_character()
    ),
    show_col_types = FALSE
  ) |>
    mutate(
      station_id = as.character(station_id),
      date = as.Date(date),
      retrieved_at = as.character(retrieved_at)
    )
}

empty_ledger <- function() {
  tibble(
    station_id = character(),
    block_start = as.Date(character()),
    block_end = as.Date(character()),
    request_status = character(),
    n_rows = integer(),
    attempted_at = character(),
    error_message = character()
  )
}

read_ledger <- function() {
  if (!file.exists(LEDGER_FILE)) return(empty_ledger())

  read_csv(
    LEDGER_FILE,
    col_types = cols(
      station_id = col_character(),
      block_start = col_date(),
      block_end = col_date(),
      request_status = col_character(),
      n_rows = col_integer(),
      attempted_at = col_character(),
      error_message = col_character()
    ),
    show_col_types = FALSE
  ) |>
    mutate(
      station_id = as.character(station_id),
      block_start = as.Date(block_start),
      block_end = as.Date(block_end),
      attempted_at = as.character(attempted_at)
    )
}

archive <- if (PARTITION_MODE) {
  empty_archive()
} else {
  read_archive()
}

ledger <- read_ledger()

completed <- ledger |>
  filter(request_status %in% c("ok_data", "ok_empty")) |>
  distinct(station_id, block_start, block_end)

if (!REFRESH_COMPLETED_BLOCKS && nrow(completed) > 0) {
  plan <- plan |>
    anti_join(
      completed,
      by = c("station_id", "block_start", "block_end")
    )
}

if (is.finite(MAX_REQUESTS_PER_RUN)) {
  plan <- plan |>
    slice_head(n = as.integer(MAX_REQUESTS_PER_RUN))
}

log_msg("Blocks per station in configured range: ", nrow(blocks))
log_msg("Requests planned this run: ", nrow(plan))

if (nrow(plan) == 0) {
  log_msg("No unfinished requests remain for this configuration.")
}

# =============================================================================
# 6. HTTP REQUEST AND RESPONSE PARSING
# =============================================================================

get_station_meta <- function(station) {
  selected_catalog |>
    filter(station_id == station) |>
    slice_head(n = 1)
}

classify_ip <- function(x) {
  case_when(
    is.na(x) ~ NA_character_,
    x <= 1 ~ "MEMENUHI BAKUMUTU",
    x < 5 ~ "CEMAR RINGAN",
    x < 10 ~ "CEMAR SEDANG",
    TRUE ~ "CEMAR BERAT"
  )
}

get_ip_block <- function(station, start_date, end_date) {
  start_date <- as.Date(start_date)
  end_date <- as.Date(end_date)

  url <- sprintf(
    "%s/trendWeekChart/id/%s/start/%s/end/%s",
    BASE_API,
    station,
    format(start_date, "%Y-%m-%d"),
    format(end_date, "%Y-%m-%d")
  )

  resp <- request(url) |>
    req_headers(
      Accept = "application/json, text/javascript, */*; q=0.01",
      `X-Requested-With` = "XMLHttpRequest",
      Referer = BASE_PAGE
    ) |>
    req_retry(max_tries = 4) |>
    req_timeout(seconds = 35) |>
    req_perform()

  resp_check_status(resp)

  x <- resp_body_json(resp, simplifyVector = TRUE)

  if (is.null(x) || length(x) == 0) {
    return(tibble())
  }

  if (is.data.frame(x)) {
    out <- as_tibble(x)
  } else if (is.list(x)) {
    out <- tryCatch(bind_rows(x), error = function(e) tibble())
  } else {
    return(tibble())
  }

  if (!all(c("tanggal", "value") %in% names(out))) {
    return(tibble())
  }

  meta <- get_station_meta(station)

  out <- out |>
    transmute(
      station_id = station,
      date = as.Date(tanggal),
      pollution_index = suppressWarnings(as.numeric(value))
    ) |>
    filter(
      !is.na(date),
      date >= start_date,
      date <= end_date
    ) |>
    distinct(station_id, date, .keep_all = TRUE) |>
    mutate(
      pollution_status_derived = classify_ip(pollution_index),
      station_name = safe_text(meta$station_name),
      river = safe_text(meta$river),
      watershed = safe_text(meta$watershed),
      location_category = safe_text(meta$location_category),
      river_segment = safe_text(meta$river_segment),
      station_category = safe_text(meta$station_category),
      kabupaten_kota = safe_text(meta$kabupaten_kota),
      province = safe_text(meta$province),
      latitude = suppressWarnings(as.numeric(meta$latitude[1])),
      longitude = suppressWarnings(as.numeric(meta$longitude[1])),
      source_endpoint = "trendWeekChart",
      retrieved_at = retrieved_at_now()
    ) |>
    select(
      station_id,
      date,
      pollution_index,
      pollution_status_derived,
      station_name,
      river,
      watershed,
      location_category,
      river_segment,
      station_category,
      kabupaten_kota,
      province,
      latitude,
      longitude,
      source_endpoint,
      retrieved_at
    )

  out
}

# =============================================================================
# 7. CHECKPOINT HELPERS
# =============================================================================

new_rows_buffer <- list()
ledger_buffer <- list()
run_rows_all <- list()

current_run_rows <- function() {
  if (length(run_rows_all) == 0L) {
    return(empty_archive())
  }

  bind_rows(run_rows_all) |>
    filter(!is.na(station_id), !is.na(date)) |>
    group_by(station_id, date) |>
    slice_tail(n = 1L) |>
    ungroup() |>
    arrange(watershed, station_id, date)
}

merge_archive <- function(old_archive, new_rows) {
  if (nrow(new_rows) == 0) return(old_archive)

  old_archive <- old_archive |>
    mutate(
      station_id = as.character(station_id),
      date = as.Date(date),
      retrieved_at = as.character(retrieved_at)
    )

  new_rows <- new_rows |>
    mutate(
      station_id = as.character(station_id),
      date = as.Date(date),
      retrieved_at = as.character(retrieved_at)
    )

  bind_rows(old_archive, new_rows) |>
    filter(!is.na(station_id), !is.na(date)) |>
    group_by(station_id, date) |>
    slice_tail(n = 1L) |>
    ungroup() |>
    arrange(watershed, station_id, date)
}

merge_ledger <- function(old_ledger, new_ledger) {
  if (nrow(new_ledger) == 0) return(old_ledger)

  bind_rows(old_ledger, new_ledger) |>
    mutate(
      block_start = as.Date(block_start),
      block_end = as.Date(block_end),
      attempted_at = as.character(attempted_at)
    ) |>
    group_by(station_id, block_start, block_end) |>
    slice_tail(n = 1L) |>
    ungroup() |>
    arrange(block_start, station_id)
}

checkpoint <- function(force = FALSE) {
  if (length(new_rows_buffer) == 0 && length(ledger_buffer) == 0 && !force) {
    return(invisible(NULL))
  }

  if (length(new_rows_buffer) > 0) {
    new_rows <- bind_rows(new_rows_buffer)
    archive <<- merge_archive(archive, new_rows)
    new_rows_buffer <<- list()
  }

  if (length(ledger_buffer) > 0) {
    new_ledger <- bind_rows(ledger_buffer)
    ledger <<- merge_ledger(ledger, new_ledger)
    ledger_buffer <<- list()
  }

  if (!PARTITION_MODE) {
    write_csv(archive, DATA_FILE, na = "")
  }

  write_csv(ledger, LEDGER_FILE, na = "")
  write_csv(current_run_rows(), RUN_ROWS_FILE, na = "")

  log_msg(
    "Checkpoint saved | archive rows in memory: ", nrow(archive),
    " | run rows: ", nrow(current_run_rows()),
    " | ledger rows: ", nrow(ledger)
  )

  invisible(NULL)
}

# =============================================================================
# 8. MAIN EXTRACTION LOOP
# =============================================================================

request_counter <- 0L
rows_this_run <- 0L
errors_this_run <- 0L
empty_this_run <- 0L

if (nrow(plan) > 0) {
  for (i in seq_len(nrow(plan))) {
    station <- plan$station_id[i]
    block_start <- plan$block_start[i]
    block_end <- plan$block_end[i]

    request_counter <- request_counter + 1L

    dat <- tryCatch(
      get_ip_block(station, block_start, block_end),
      error = function(e) {
        errors_this_run <<- errors_this_run + 1L

        ledger_buffer[[length(ledger_buffer) + 1L]] <<- tibble(
          station_id = station,
          block_start = as.Date(block_start),
          block_end = as.Date(block_end),
          request_status = "error",
          n_rows = 0L,
          attempted_at = retrieved_at_now(),
          error_message = conditionMessage(e)
        )

        log_msg(
          "ERROR | ", station,
          " | ", block_start, " to ", block_end,
          " | ", conditionMessage(e)
        )

        NULL
      }
    )

    if (!is.null(dat)) {
      if (nrow(dat) > 0) {
        new_rows_buffer[[length(new_rows_buffer) + 1L]] <- dat
        run_rows_all[[length(run_rows_all) + 1L]] <- dat
        rows_this_run <- rows_this_run + nrow(dat)
        status <- "ok_data"
      } else {
        empty_this_run <- empty_this_run + 1L
        status <- "ok_empty"
      }

      ledger_buffer[[length(ledger_buffer) + 1L]] <- tibble(
        station_id = station,
        block_start = as.Date(block_start),
        block_end = as.Date(block_end),
        request_status = status,
        n_rows = as.integer(nrow(dat)),
        attempted_at = retrieved_at_now(),
        error_message = NA_character_
      )
    }

    if (
      request_counter %% CHECKPOINT_EVERY == 0L ||
      request_counter == nrow(plan)
    ) {
      checkpoint()
      log_msg(
        "Progress: ", request_counter, "/", nrow(plan),
        " requests | rows retrieved: ", rows_this_run,
        " | empty blocks: ", empty_this_run,
        " | errors: ", errors_this_run
      )
    }

    Sys.sleep(
      runif(
        1,
        REQUEST_PAUSE_MIN_SEC,
        REQUEST_PAUSE_MAX_SEC
      )
    )
  }
}

checkpoint(force = TRUE)

# =============================================================================
# 9. COVERAGE AND MONTHLY DIAGNOSTICS
# =============================================================================

if (!PARTITION_MODE && nrow(archive) > 0) {
  coverage <- archive |>
    group_by(
      station_id,
      station_name,
      river,
      watershed,
      station_category,
      kabupaten_kota,
      province
    ) |>
    summarise(
      first_date = min(date, na.rm = TRUE),
      last_date = max(date, na.rm = TRUE),
      n_records = n_distinct(date),
      observed_span_days = as.integer(last_date - first_date) + 1L,
      completeness_within_observed_span_pct =
        100 * n_records / observed_span_days,
      mean_ip = if (all(is.na(pollution_index))) NA_real_ else mean(pollution_index, na.rm = TRUE),
      median_ip = if (all(is.na(pollution_index))) NA_real_ else median(pollution_index, na.rm = TRUE),
      max_ip = if (all(is.na(pollution_index))) NA_real_ else max(pollution_index, na.rm = TRUE),
      pct_meets_standard = 100 * mean(pollution_index <= 1, na.rm = TRUE),
      pct_light = 100 * mean(pollution_index > 1 & pollution_index < 5, na.rm = TRUE),
      pct_moderate = 100 * mean(pollution_index >= 5 & pollution_index < 10, na.rm = TRUE),
      pct_heavy = 100 * mean(pollution_index >= 10, na.rm = TRUE),
      .groups = "drop"
    ) |>
    arrange(watershed, station_id)

  write_csv(coverage, COVERAGE_FILE, na = "")

  monthly <- archive |>
    mutate(
      year = as.integer(format(date, "%Y")),
      month = as.integer(format(date, "%m")),
      year_month = format(date, "%Y-%m")
    ) |>
    group_by(
      station_id,
      station_name,
      river,
      watershed,
      station_category,
      year,
      month,
      year_month
    ) |>
    summarise(
      n_days = n_distinct(date),
      mean_ip = if (all(is.na(pollution_index))) NA_real_ else mean(pollution_index, na.rm = TRUE),
      median_ip = if (all(is.na(pollution_index))) NA_real_ else median(pollution_index, na.rm = TRUE),
      max_ip = if (all(is.na(pollution_index))) NA_real_ else max(pollution_index, na.rm = TRUE),
      pct_meets_standard = 100 * mean(pollution_index <= 1, na.rm = TRUE),
      pct_light = 100 * mean(pollution_index > 1 & pollution_index < 5, na.rm = TRUE),
      pct_moderate = 100 * mean(pollution_index >= 5 & pollution_index < 10, na.rm = TRUE),
      pct_heavy = 100 * mean(pollution_index >= 10, na.rm = TRUE),
      .groups = "drop"
    ) |>
    arrange(watershed, station_id, year, month)

  write_csv(monthly, MONTHLY_FILE, na = "")
}

if (PARTITION_MODE) {
  log_msg(
    "Partition mode active: cumulative coverage/monthly diagnostics were not ",
    "written because the GitHub worker intentionally restores only the request ledger."
  )
}

# =============================================================================
# 10. FINAL RUN SUMMARY
# =============================================================================

completed_after <- ledger |>
  filter(request_status %in% c("ok_data", "ok_empty")) |>
  semi_join(
    tidyr::crossing(
      block_start = blocks$block_start,
      station_id = selected_catalog$station_id
    ) |>
      left_join(blocks, by = "block_start"),
    by = c("station_id", "block_start", "block_end")
  ) |>
  distinct(station_id, block_start, block_end)

expected_total <- nrow(blocks) * nrow(selected_catalog)
completed_total <- nrow(completed_after)
remaining_total <- max(0L, expected_total - completed_total)

run_rows_final <- current_run_rows()
write_csv(run_rows_final, RUN_ROWS_FILE, na = "")

run_summary <- tibble(
  run_started_at = format(
    run_started,
    "%Y-%m-%d %H:%M:%S%z",
    tz = COLLECTOR_TZ
  ),
  run_finished_at = retrieved_at_now(),
  collector_id = COLLECTOR_ID,
  github_run_id = optional_env_value(GITHUB_RUN_ID),
  github_run_attempt = optional_env_value(GITHUB_RUN_ATTEMPT),
  scraper_code_commit = optional_env_value(GITHUB_SHA),
  scope_mode = SCOPE_MODE,
  start_date = as.character(START_DATE),
  end_date = as.character(END_DATE),
  stations_selected = nrow(selected_catalog),
  blocks_per_station = nrow(blocks),
  expected_requests = expected_total,
  requests_attempted = request_counter,
  rows_retrieved = rows_this_run,
  empty_blocks = empty_this_run,
  errors = errors_this_run,
  completed_requests = completed_total,
  remaining_requests = remaining_total,
  partition_mode = PARTITION_MODE
)

write_csv(run_summary, RUN_SUMMARY_FILE, na = "")

log_msg("Requests attempted this run: ", request_counter)
log_msg("Daily IP rows retrieved this run: ", rows_this_run)
log_msg("Empty blocks this run: ", empty_this_run)
log_msg("Errors this run: ", errors_this_run)
log_msg("Run partition rows: ", nrow(run_rows_final))
if (!PARTITION_MODE) {
  log_msg("Archive rows total: ", nrow(archive))
}
log_msg(
  "Configured block progress: ", completed_total,
  "/", expected_total,
  " completed; ", remaining_total, " remain"
)
log_msg("Run summary: ", RUN_SUMMARY_FILE)
log_msg("FINISH historical Pollution Index extraction")

# Exit non-zero only when every attempted request failed.
if (request_counter > 0L && errors_this_run == request_counter) {
  quit(save = "no", status = 1)
}

quit(save = "no", status = 0)